### ISSUE TITLE
P01 - Structuration du projet

### ISSUE THREAD

**Issue by Alexia50** [SK0RPIA/CMS-SLAM#18]
Optimisation de l'arborescence du projet, mise en forme des dossiers et du classement du fichier

**Comment by jcheron** [comment]
Les assets seraient mieux dans un dossier `public/assets`
Ce dossier `public` devra contenir les éléments directement accessible depuis Internet uniquement...
donc pas les fichiers php qui ne font que des déclarations (de classes ou de fonctions) comme la classe `Database` par exemple
@SK0RPIA @Matteotr9

**Comment by Alexia50** [comment]
probleme rectifié, RAS
